-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientDx
local SlipeClientEnums
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientDx = Slipe.Client.Dx
  SlipeClientEnums = Slipe.Client.Enums
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- Class representing custom font elements
  -- </summary>
  namespace.class("Font", function (namespace)
    local getMTAFont, GetHeight, GetHeight1, GetHeight2, class, __ctor__
    -- <summary>
    -- Create a new font from a path
    -- </summary>
    __ctor__ = function (this, filePath, size, bold, quality)
      this._font = SlipeMtaDefinitions.MtaClient.DxCreateFont(filePath, size, bold, quality:ToEnumString(SlipeClientEnums.FontQuality):ToLower())
    end
    getMTAFont = function (this)
      return this._font
    end
    -- <summary>
    -- Get the height of this font
    -- </summary>
    GetHeight = function (this, scale)
      return SlipeMtaDefinitions.MtaClient.DxGetFontHeight(scale, this._font)
    end
    -- <summary>
    -- Get the height of a GTA font
    -- </summary>
    GetHeight1 = function (font, scale)
      return SlipeMtaDefinitions.MtaClient.DxGetFontHeight(scale, font:ToEnumString(SlipeClientDx.StandardFont):ToLower())
    end
    -- <summary>
    -- Get the height of a custom font
    -- </summary>
    GetHeight2 = function (font, scale)
      return SlipeMtaDefinitions.MtaClient.DxGetFontHeight(scale, getMTAFont(font))
    end
    class = {
      getMTAFont = getMTAFont,
      GetHeight = GetHeight,
      GetHeight1 = GetHeight1,
      GetHeight2 = GetHeight2,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "_font", 0x1, out.Slipe.MtaDefinitions.MtaElement }
          },
          properties = {
            { "MTAFont", 0x206, out.Slipe.MtaDefinitions.MtaElement, getMTAFont }
          },
          methods = {
            { ".ctor", 0x406, nil, System.String, System.Int32, System.Boolean, System.Int32 },
            { "GetHeight", 0x186, GetHeight, System.Single, System.Int32 },
            { "GetHeight", 0x28E, GetHeight1, System.Int32, System.Single, System.Int32 },
            { "GetHeight", 0x28E, GetHeight2, class, System.Single, System.Int32 }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)
end)
