-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- Represents the standard fonts built into GTA
  -- </summary>
  namespace.enum("StandardFont", function ()
    return {
      Default = 0,
      Clear = 1,
      Arial = 2,
      Sans = 3,
      Pricedown = 4,
      BankGothic = 5,
      Diploma = 6,
      Beckett = 7
    }
  end)
end)
