-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientDx
local SlipeMtaDefinitions
local SlipeSharedUtilities
local SystemNumerics
System.import(function (out)
  SlipeClientDx = Slipe.Client.Dx
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedUtilities = Slipe.Shared.Utilities
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Dx", function (namespace)
  -- <summary>
  -- Drawable texture
  -- </summary>
  namespace.class("Texture", function (namespace)
    local GetPixels, GetPixels1, SetEdge, SetEdge1, SetPixels, __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this)
      SlipeClientDx.Material.__ctor__(this)
    end
    -- <summary>
    -- Create a texture element from a file or raw image string
    -- </summary>
    __ctor2__ = function (this, filePathOrPixels, textureFormat, mipmaps, textureEdge)
      SlipeClientDx.Material.__ctor__(this)
      this.materialElement = SlipeMtaDefinitions.MtaClient.DxCreateTexture(filePathOrPixels, textureFormat:ToEnumString(SlipeClientDx.TextureFormat):ToLower(), mipmaps, textureEdge:ToEnumString(SlipeClientDx.TextureEdge):ToLower())
    end
    -- <summary>
    -- Create an empty texture
    -- </summary>
    __ctor3__ = function (this, dimensions, textureFormat, textureEdge, textureType, depth)
      SlipeClientDx.Material.__ctor__(this)
      local textureTypeString = "cube"
      if textureType == 0 --[[TextureType.TwoDimensional]] then
        textureTypeString = "2d"
      elseif textureType == 1 --[[TextureType.ThreeDimensional]] then
        textureTypeString = "3d"
      end

      this.materialElement = SlipeMtaDefinitions.MtaClient.DxCreateTexture(System.ToInt32(dimensions.X), System.ToInt32(dimensions.Y), textureFormat:ToEnumString(SlipeClientDx.TextureFormat):ToLower(), textureEdge:ToEnumString(SlipeClientDx.TextureEdge):ToLower(), textureTypeString, depth)
    end
    -- <summary>
    -- Get the pixels of a section of this texture
    -- </summary>
    GetPixels = function (this, topLeft, dimensions, surfaceIndex)
      return SlipeClientDx.TexturePixels(SlipeMtaDefinitions.MtaClient.DxGetTexturePixels(surfaceIndex, this.materialElement, System.ToInt32(topLeft.X), System.ToInt32(topLeft.Y), System.ToInt32(dimensions.X), System.ToInt32(dimensions.Y)))
    end
    -- <summary>
    -- Get all pixels of this texture
    -- </summary>
    GetPixels1 = function (this, surfaceIndex)
      return GetPixels(this, SystemNumerics.Vector2.getZero(), SystemNumerics.Vector2.getZero(), surfaceIndex)
    end
    -- <summary>
    -- This functions allows you to change the edge handling after creating the texture.
    -- </summary>
    SetEdge = function (this, edge, borderColor)
      return SlipeMtaDefinitions.MtaClient.DxSetTextureEdge(this.materialElement, edge == 4 --[[TextureEdge.MirrorOnce]] and "mirror-once" or edge:ToEnumString(SlipeClientDx.TextureEdge), borderColor:getHex())
    end
    -- <summary>
    -- Change edge handling with white border if border is selected
    -- </summary>
    SetEdge1 = function (this, edge)
      return SetEdge(this, edge, SlipeSharedUtilities.Color.getWhite())
    end
    -- <summary>
    -- This function sets the pixels of a texture element. It can be used with a standard texture, render target or screen source.
    -- </summary>
    SetPixels = function (this, pixels, topLeft, dimensions, surfaceIndex)
      local p = pixels:Convert(0 --[[ImageFormat.plain]], 80)
      return SlipeMtaDefinitions.MtaClient.DxSetTexturePixels(surfaceIndex, this.materialElement, p, System.ToInt32(topLeft.X), System.ToInt32(topLeft.Y), System.ToInt32(dimensions.X), System.ToInt32(dimensions.Y))
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Dx.Material
        }
      end,
      GetPixels = GetPixels,
      GetPixels1 = GetPixels1,
      SetEdge = SetEdge,
      SetEdge1 = SetEdge1,
      SetPixels = SetPixels,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x3, __ctor1__ },
            { ".ctor", 0x406, __ctor2__, System.String, System.Int32, System.Boolean, System.Int32 },
            { ".ctor", 0x506, __ctor3__, System.Numerics.Vector2, System.Int32, System.Int32, System.Int32, System.Int32 },
            { "GetPixels", 0x386, GetPixels, System.Numerics.Vector2, System.Numerics.Vector2, System.Int32, out.Slipe.Client.Dx.TexturePixels },
            { "GetPixels", 0x186, GetPixels1, System.Int32, out.Slipe.Client.Dx.TexturePixels },
            { "SetEdge", 0x286, SetEdge, System.Int32, out.Slipe.Shared.Utilities.Color, System.Boolean },
            { "SetEdge", 0x186, SetEdge1, System.Int32, System.Boolean },
            { "SetPixels", 0x486, SetPixels, out.Slipe.Client.Dx.TexturePixels, System.Numerics.Vector2, System.Numerics.Vector2, System.Int32, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
