-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Game", function (namespace)
  -- <summary>
  -- Represents the input mode for Gui's
  -- </summary>
  namespace.enum("InputMode", function ()
    return {
      Allow_Binds = 0,
      No_Binds = 1,
      No_Binds_When_Editing = 2
    }
  end)
end)
