-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Game", function (namespace)
  -- <summary>
  -- Represents windows notificatoin tray icons
  -- </summary>
  namespace.enum("TrayIconType", function ()
    return {
      Default = 0,
      Info = 1,
      Warning = 2,
      Error = 3
    }
  end)
end)
