-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedRadar
local SlipeSharedUtilities
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedRadar = Slipe.Shared.Radar
  SlipeSharedUtilities = Slipe.Shared.Utilities
end)
System.namespace("Slipe.Client.Radar", function (namespace)
  -- <summary>
  -- Class representing a minimap blip
  -- </summary>
  namespace.class("Blip", function (namespace)
    local __ctor1__, __ctor2__, __ctor3__, __ctor4__, __ctor5__
    __ctor1__ = function (this, element)
      SlipeSharedRadar.SharedBlip.__ctor__(this, element)
    end
    -- <summary>
    -- Creates a blip from all the createBlip parameters
    -- </summary>
    __ctor2__ = function (this, vector, icon, color, size, ordering, visibleDistance)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.CreateBlip(vector.X, vector.Y, vector.Z, icon, size, color:getR(), color:getG(), color:getB(), color:getA(), ordering, visibleDistance))
    end
    -- <summary>
    -- Creates a standard red blip
    -- </summary>
    __ctor3__ = function (this, vector)
      __ctor2__(this, vector:__clone__(), 0, SlipeSharedUtilities.Color.getRed(), 2, 0, 16383)
    end
    -- <summary>
    -- Creates a blip attached to an MTA element
    -- </summary>
    __ctor4__ = function (this, physicalElement, icon, color, size, ordering, visibleDistance)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.CreateBlipAttachedTo(physicalElement:getMTAElement(), icon, size, color:getR(), color:getG(), color:getB(), color:getA(), ordering, visibleDistance))
    end
    -- <summary>
    -- Creates a standard red blip attached to an  MTA element
    -- </summary>
    __ctor5__ = function (this, physicalElement)
      __ctor4__(this, physicalElement, 0, SlipeSharedUtilities.Color.getRed(), 2, 0, 16383)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Radar.SharedBlip
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__,
        __ctor4__,
        __ctor5__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x606, __ctor2__, System.Numerics.Vector3, System.Int32, out.Slipe.Shared.Utilities.Color, System.Int32, System.Int32, System.Single },
            { ".ctor", 0x106, __ctor3__, System.Numerics.Vector3 },
            { ".ctor", 0x606, __ctor4__, out.Slipe.Shared.Elements.PhysicalElement, System.Int32, out.Slipe.Shared.Utilities.Color, System.Int32, System.Int32, System.Single },
            { ".ctor", 0x106, __ctor5__, out.Slipe.Shared.Elements.PhysicalElement }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 8 --[[ElementType.Blip]]) }
        }
      end
    }
  end)
end)
