-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGame
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientGame = Slipe.Client.Game
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Assets", function (namespace)
  -- <summary>
  -- Represents a single asset file.
  -- </summary>
  namespace.class("Asset", function (namespace)
    local getFilepath, getState, HandleDownloadComplete, Download, __ctor__
    -- <summary>
    -- Creates a new asset with a specific filepath;
    -- </summary>
    __ctor__ = function (this, filepath)
      this.state = 0 --[[DownloadState.Default]]
      this.filepath = filepath

      SlipeClientGame.GameClient.OnFileDownloadComplete = SlipeClientGame.GameClient.OnFileDownloadComplete + System.fn(this, HandleDownloadComplete)
    end
    getFilepath = function (this)
      return this.filepath
    end
    getState = function (this)
      return this.state
    end
    HandleDownloadComplete = function (this, source, eventArgs)
      if eventArgs.Path == this.filepath then
        this.state = eventArgs.Success and 2 --[[DownloadState.Downloaded]] or 3 --[[DownloadState.Failed]]
        SlipeClientGame.GameClient.OnFileDownloadComplete = SlipeClientGame.GameClient.OnFileDownloadComplete - System.fn(this, HandleDownloadComplete)
        local default = this.OnDownloadComplete
        if default ~= nil then
          default()
        end
      end
    end
    -- <summary>
    -- Starts a download of the file
    -- </summary>
    Download = function (this)
      this.state = 1 --[[DownloadState.Downloading]]
      SlipeMtaDefinitions.MtaClient.DownloadFile(this.filepath)
    end
    return {
      getFilepath = getFilepath,
      state = 0,
      getState = getState,
      Download = Download,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "filepath", 0x3, System.String },
            { "state", 0x3, System.Int32 }
          },
          properties = {
            { "Filepath", 0x206, System.String, getFilepath },
            { "State", 0x206, System.Int32, getState }
          },
          methods = {
            { ".ctor", 0x106, nil, System.String },
            { "Download", 0x6, Download },
            { "HandleDownloadComplete", 0x201, HandleDownloadComplete, out.Slipe.Client.Elements.ResourceRootElement, out.Slipe.Client.Game.Events.OnFileDownloadCompleteEventArgs }
          },
          events = {
            { "OnDownloadComplete", 0x6, System.Delegate }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
