-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientAssets
local SlipeMtaDefinitions
System.import(function (out)
  SlipeClientAssets = Slipe.Client.Assets
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Assets", function (namespace)
  namespace.class("Ifp", function (namespace)
    local Load, __ctor__
    __ctor__ = function (this, filepath)
      SlipeClientAssets.Asset.__ctor__(this, filepath)
    end
    -- <summary>
    -- Loads the IFP file into the animation block
    -- </summary>
    Load = function (this, customBlockName)
      this.ifp = SlipeMtaDefinitions.MtaClient.EngineLoadIFP(this.filepath, customBlockName)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Assets.Asset
        }
      end,
      Load = Load,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "ifp", 0x1, out.Slipe.MtaDefinitions.MtaElement }
          },
          methods = {
            { ".ctor", 0x106, nil, System.String },
            { "Load", 0x106, Load, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
