-- Generated by CSharp.lua Compiler
local System = System
local SystemNumerics
System.import(function (out)
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Elements.Events", function (namespace)
  namespace.class("OnWorldSoundEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, group, index, x, y, z)
      this.Position = System.default(SystemNumerics.Vector3)
      this.Group = System.cast(System.Int32, group)
      this.Index = System.cast(System.Int32, index)
      this.Position = SystemNumerics.Vector3(System.cast(System.Single, x), System.cast(System.Single, y), System.cast(System.Single, z))
    end
    return {
      Group = 0,
      Index = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Group", 0x6, System.Int32 },
            { "Index", 0x6, System.Int32 },
            { "Position", 0x6, System.Numerics.Vector3 }
          },
          methods = {
            { ".ctor", 0x504, nil, System.Object, System.Object, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
