-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Markers", function (namespace)
  namespace.enum("MarkerIcon", function ()
    return {
      None = 0,
      Arrow = 1,
      Finish = 2
    }
  end)
end)
