-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Markers", function (namespace)
  -- <summary>
  -- Represents different types of markers
  -- </summary>
  namespace.enum("MarkerType", function ()
    return {
      Checkpoint = 0,
      Ring = 1,
      Cylinder = 2,
      Arrow = 3,
      Corona = 4
    }
  end)
end)
