-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.GameWorld", function (namespace)
  -- <summary>
  -- Represents the different states of traffic lights in the world
  -- </summary>
  namespace.enum("TrafficLightState", function ()
    return {
      NSGreen = 0,
      NSYellow = 1,
      AllRed = 2,
      EWGreen = 3,
      EWYellow = 4,
      AllGreen = 5,
      AllYellow = 6,
      NSYellowEWGreen = 7,
      EWYellowNSGreen = 8,
      Disabled = 9,
      Auto = 10
    }
  end)
end)
