-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientPeds
local SlipeMtaDefinitions
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeClientPeds = Slipe.Client.Peds
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Weapons", function (namespace)
  -- <summary>
  -- Represents a custom projectile
  -- </summary>
  namespace.class("Projectile", function (namespace)
    local getCounter, setCounter, getCreator, getTarget, getForce, getProjectileType, class, __ctor1__, 
    __ctor2__, __ctor3__, __ctor4__, __ctor5__
    __ctor1__ = function (this, element)
      SlipeSharedElements.PhysicalElement.__ctor__(this, element)
    end
    -- <summary>
    -- Create a new projectile with all the parameters
    -- </summary>
    __ctor2__ = function (this, creator, projectile, startPos, force, target, rotation, velocity, model)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.CreateProjectile(creator:getMTAElement(), projectile, startPos.X, startPos.Y, startPos.Z, force, target:getMTAElement(), rotation.X, rotation.Y, rotation.Z, velocity.X, velocity.Y, velocity.Z, - 1))
    end
    -- <summary>
    -- Create a new projectile
    -- </summary>
    __ctor3__ = function (this, creator, projectile, startPos, force, target, rotation)
      __ctor2__(this, creator, projectile, startPos:__clone__(), force, target, rotation:__clone__(), SystemNumerics.Vector3.getZero(), -1)
    end
    -- <summary>
    -- Create a new projectile
    -- </summary>
    __ctor4__ = function (this, creator, projectile, startPos, force, target)
      __ctor3__(this, creator, projectile, startPos:__clone__(), force, target, SystemNumerics.Vector3.getZero())
    end
    -- <summary>
    -- Create a new projectile
    -- </summary>
    __ctor5__ = function (this, creator, projectile, startPos, force)
      __ctor4__(this, creator, projectile, startPos:__clone__(), force)
    end
    getCounter = function (this)
      return SlipeMtaDefinitions.MtaClient.GetProjectileCounter(this.element)
    end
    setCounter = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetProjectileCounter(this.element, value)
    end
    getCreator = function (this)
      local default, extern = System.try(function ()
        return true, SlipeSharedElements.ElementManager.getInstance():GetElement(SlipeMtaDefinitions.MtaClient.GetProjectileCreator(this.element), SlipeClientPeds.Player)
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getTarget = function (this)
      local default, extern = System.try(function ()
        return true, SlipeSharedElements.ElementManager.getInstance():GetElement(SlipeMtaDefinitions.MtaClient.GetProjectileTarget(this.element), SlipeSharedElements.PhysicalElement)
      end, function (default)
        if System.is(default, SlipeMtaDefinitions.MtaException) then
          return true, nil
        else
          return 1, default
        end
      end)
      if default then
        return extern
      end
    end
    getForce = function (this)
      return SlipeMtaDefinitions.MtaClient.GetProjectileForce(this.element)
    end
    getProjectileType = function (this)
      return SlipeMtaDefinitions.MtaClient.GetProjectileType(this.element)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.PhysicalElement
        }
      end,
      getCounter = getCounter,
      setCounter = setCounter,
      getCreator = getCreator,
      getTarget = getTarget,
      getForce = getForce,
      getProjectileType = getProjectileType,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__,
        __ctor4__,
        __ctor5__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Counter", 0x106, System.Int32, getCounter, setCounter },
            { "Creator", 0x206, out.Slipe.Client.Peds.Player, getCreator },
            { "Force", 0x206, System.Single, getForce },
            { "ProjectileType", 0x206, System.Int32, getProjectileType },
            { "Target", 0x206, out.Slipe.Shared.Elements.PhysicalElement, getTarget }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x806, __ctor2__, out.Slipe.Shared.Elements.PhysicalElement, System.Int32, System.Numerics.Vector3, System.Single, out.Slipe.Shared.Elements.PhysicalElement, System.Numerics.Vector3, System.Numerics.Vector3, System.Int32 },
            { ".ctor", 0x606, __ctor3__, out.Slipe.Shared.Elements.PhysicalElement, System.Int32, System.Numerics.Vector3, System.Single, out.Slipe.Shared.Elements.PhysicalElement, System.Numerics.Vector3 },
            { ".ctor", 0x506, __ctor4__, out.Slipe.Shared.Elements.PhysicalElement, System.Int32, System.Numerics.Vector3, System.Single, out.Slipe.Shared.Elements.PhysicalElement },
            { ".ctor", 0x406, __ctor5__, out.Slipe.Shared.Elements.PhysicalElement, System.Int32, System.Numerics.Vector3, System.Single }
          },
          events = {
            { "OnCreated", 0x6, System.Delegate(class, out.Slipe.Client.Weapons.Events.OnCreatedEventArgs, System.Void) }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 10 --[[ElementType.Projectile]]) }
        }
      end
    }
    return class
  end)
end)
