-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerVehicles
local SystemNumerics
System.import(function (out)
  SlipeServerVehicles = Slipe.Server.Vehicles
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Server.Vehicles", function (namespace)
  -- <summary>
  -- Class representing all regular vehicle types
  -- </summary>
  namespace.class("Vehicle", function (namespace)
    local __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this, element)
      SlipeServerVehicles.BaseVehicle.__ctor__[1](this, element)
    end
    -- <summary>
    -- Create a vehicle from a model at a position
    -- </summary>
    __ctor2__ = function (this, model, position)
      __ctor3__(this, model, position:__clone__(), SystemNumerics.Vector3.getZero(), "", 1, 1)
    end
    -- <summary>
    -- Create a vehicle using all createVehicle arguments
    -- </summary>
    __ctor3__ = function (this, model, position, rotation, numberplate, variant1, variant2)
      SlipeServerVehicles.BaseVehicle.__ctor__[2](this, model, position:__clone__(), rotation:__clone__(), numberplate, variant1, variant2)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Server.Vehicles.BaseVehicle
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x206, __ctor2__, out.Slipe.Server.Vehicles.VehicleModel, System.Numerics.Vector3 },
            { ".ctor", 0x606, __ctor3__, out.Slipe.Server.Vehicles.VehicleModel, System.Numerics.Vector3, System.Numerics.Vector3, System.String, System.Int32, System.Int32 }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 3 --[[ElementType.Vehicle]]) }
        }
      end
    }
  end)
end)
