-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedRpc
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedRpc = Slipe.Shared.Rpc
end)
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("ElementRpc", function (namespace)
    local Parse, __ctor1__, __ctor2__
    __ctor1__ = function (this)
      SlipeSharedRpc.BaseRpc.__ctor__(this)
    end
    __ctor2__ = function (this, element)
      SlipeSharedRpc.BaseRpc.__ctor__(this)
      this.Element = element
    end
    Parse = function (this, value)
      this.Element = this:GetElement(value.Element, SlipeSharedElements.Element)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.BaseRpc
        }
      end,
      Parse = Parse,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Element", 0x6, out.Slipe.Shared.Elements.Element }
          },
          methods = {
            { ".ctor", 0x6, __ctor1__ },
            { ".ctor", 0x106, __ctor2__, out.Slipe.Shared.Elements.Element },
            { "Parse", 0x106, Parse, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)

  namespace.class("ElementRpc_1", function (namespace)
    return function (ElementType)
      local Parse, __ctor1__, __ctor2__
      __ctor1__ = function (this)
        SlipeSharedRpc.BaseRpc.__ctor__(this)
      end
      __ctor2__ = function (this, element)
        SlipeSharedRpc.BaseRpc.__ctor__(this)
        this.Element = element
      end
      Parse = function (this, value)
        this.Element = this:GetElement(value.Element, ElementType)
      end
      return {
        __inherits__ = function (out)
          return {
            out.Slipe.Shared.Rpc.BaseRpc
          }
        end,
        Parse = Parse,
        __ctor__ = {
          __ctor1__,
          __ctor2__
        },
        __metadata__ = function (out)
          return {
            properties = {
              { "Element", 0x6, ElementType }
            },
            methods = {
              { ".ctor", 0x6, __ctor1__ },
              { ".ctor", 0x106, __ctor2__, ElementType },
              { "Parse", 0x106, Parse, System.Object }
            },
            class = { 0x106, ElementType }
          }
        end
      }
    end
  end)
end)
