-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedRpc
System.import(function (out)
  SlipeSharedRpc = Slipe.Shared.Rpc
end)
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("SingleCastRpc_1", function (namespace)
    return function (T)
      local Parse, internal, __ctor1__, __ctor2__
      internal = function (this)
        this.Value = System.default(T)
      end
      __ctor1__ = function (this)
        internal(this)
        SlipeSharedRpc.BaseRpc.__ctor__(this)
      end
      __ctor2__ = function (this, value)
        internal(this)
        SlipeSharedRpc.BaseRpc.__ctor__(this)
        this.Value = value
      end
      Parse = function (this, value)
        this.Value = System.cast(T, value.Value)
      end
      return {
        __inherits__ = function (out)
          return {
            out.Slipe.Shared.Rpc.BaseRpc
          }
        end,
        Parse = Parse,
        __ctor__ = {
          __ctor1__,
          __ctor2__
        },
        __metadata__ = function (out)
          return {
            properties = {
              { "Value", 0x6, T }
            },
            methods = {
              { ".ctor", 0x6, __ctor1__ },
              { ".ctor", 0x106, __ctor2__, T },
              { "Parse", 0x106, Parse, System.Object }
            },
            class = { 0x106, T }
          }
        end
      }
    end
  end)
end)
