-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerMarkers
local SlipeSharedElements
System.import(function (out)
  SlipeServerMarkers = Slipe.Server.Markers
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnMarkerHitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, markerHit, matchingDimension)
      this.Marker = SlipeSharedElements.ElementManager.getInstance():GetElement(markerHit, SlipeServerMarkers.Marker)
      this.IsDimensionMatching = System.cast(System.Boolean, matchingDimension)
    end
    return {
      IsDimensionMatching = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "IsDimensionMatching", 0x6, System.Boolean },
            { "Marker", 0x6, out.Slipe.Server.Markers.Marker }
          },
          methods = {
            { ".ctor", 0x204, nil, out.Slipe.MtaDefinitions.MtaElement, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
