-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerWeapons
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeServerWeapons = Slipe.Server.Weapons
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Server.Peds.Events", function (namespace)
  namespace.class("OnWeaponFireEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, weapon, ex, ey, ez, hitElement, sx, sy, sz)
      this.EndPosition = System.default(SystemNumerics.Vector3)
      this.StartPosition = System.default(SystemNumerics.Vector3)
      this.Weapon = System.new(SlipeServerWeapons.WeaponModel, 2, System.cast(System.Int32, weapon))
      this.HitElement = SlipeSharedElements.ElementManager.getInstance():GetElement(hitElement, SlipeSharedElements.PhysicalElement)
      this.EndPosition = SystemNumerics.Vector3(System.cast(System.Single, ex), System.cast(System.Single, ey), System.cast(System.Single, ez))
      this.StartPosition = SystemNumerics.Vector3(System.cast(System.Single, sx), System.cast(System.Single, sy), System.cast(System.Single, sz))
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "EndPosition", 0x6, System.Numerics.Vector3 },
            { "HitElement", 0x6, out.Slipe.Shared.Elements.PhysicalElement },
            { "StartPosition", 0x6, System.Numerics.Vector3 },
            { "Weapon", 0x6, out.Slipe.Server.Weapons.WeaponModel }
          },
          methods = {
            { ".ctor", 0x804, nil, System.Object, System.Object, System.Object, System.Object, out.Slipe.MtaDefinitions.MtaElement, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
