-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
local ArrayMtaElement
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  ArrayMtaElement = System.Array(SlipeMtaDefinitions.MtaElement)
end)
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("BaseRpc", function (namespace)
    local GetArray, CreateElementArray, GetElementArray, GetElement
    GetArray = function (this, table, T)
      return SlipeMtaDefinitions.MtaShared.GetArrayFromTable(table, "", T)
    end
    CreateElementArray = function (this, elements)
      local mtaElements = ArrayMtaElement:new(#elements)

      for i = 0, #elements - 1 do
        mtaElements:set(i, elements:get(i):getMTAElement())
      end

      return mtaElements
    end
    GetElementArray = function (this, table, T)
      local mtaElements = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(table, "", SlipeMtaDefinitions.MtaElement)

      local elements = System.Array(T):new(#mtaElements)
      for i = 0, #mtaElements - 1 do
        elements:set(i, SlipeSharedElements.ElementManager.getInstance():GetElement(mtaElements:get(i), T))
      end
      return elements
    end
    GetElement = function (this, mtaElement, T)
      return SlipeSharedElements.ElementManager.getInstance():GetElement(mtaElement.element, T)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.IRpc
        }
      end,
      GetArray = GetArray,
      CreateElementArray = CreateElementArray,
      GetElementArray = GetElementArray,
      GetElement = GetElement,
      __metadata__ = function (out)
        return {
          methods = {
            { "CreateElementArray", 0x183, CreateElementArray, System.Array(out.Slipe.Shared.Elements.Element), System.Array(out.Slipe.MtaDefinitions.MtaElement) },
            { "GetArray", 0x10183, GetArray, function (T) return System.Object, System.Array(T) end },
            { "GetElement", 0x10183, GetElement, function (T) return System.Object, T end },
            { "GetElementArray", 0x10183, GetElementArray, function (T) return System.Object, System.Array(T) end }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
