-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("EmptyRpc", function (namespace)
    local Parse
    Parse = function (this, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.IRpc
        }
      end,
      Parse = Parse,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil },
            { "Parse", 0x106, Parse, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
