-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Rpc", function (namespace)
  namespace.class("EmptyOutgoingRpc", function (namespace)
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Rpc.IRpc
        }
      end,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x6, nil }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
