-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Weapons.Events", function (namespace)
  namespace.class("OnCreatedEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, element)
      this.Creator = SlipeSharedElements.ElementManager.getInstance():GetElement(element, SlipeSharedElements.PhysicalElement)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Creator", 0x6, out.Slipe.Shared.Elements.PhysicalElement }
          },
          methods = {
            { ".ctor", 0x104, nil, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
