-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Weapons.Events", function (namespace)
  namespace.class("OnFireEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, hitElement, x, y, z, nx, ny, nz, hitMaterial, lighting, partHit)
      this.Position = System.default(SystemNumerics.Vector3)
      this.Normal = System.default(SystemNumerics.Vector3)
      this.HitElement = SlipeSharedElements.ElementManager.getInstance():GetElement(hitElement, SlipeSharedElements.PhysicalElement)
      this.Position = SystemNumerics.Vector3(System.cast(System.Single, x), System.cast(System.Single, y), System.cast(System.Single, z))
      this.Normal = SystemNumerics.Vector3(System.cast(System.Single, nx), System.cast(System.Single, ny), System.cast(System.Single, nz))
      this.Material = System.cast(System.Int32, hitMaterial)
      this.Lighting = System.cast(System.Single, lighting)
      this.Piece = System.cast(System.Int32, partHit)
    end
    return {
      Material = 0,
      Lighting = 0,
      Piece = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "HitElement", 0x6, out.Slipe.Shared.Elements.PhysicalElement },
            { "Lighting", 0x6, System.Single },
            { "Material", 0x6, System.Int32 },
            { "Normal", 0x6, System.Numerics.Vector3 },
            { "Piece", 0x6, System.Int32 },
            { "Position", 0x6, System.Numerics.Vector3 }
          },
          methods = {
            { ".ctor", 0xA04, nil, out.Slipe.MtaDefinitions.MtaElement, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
