-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerResources
System.import(function (out)
  SlipeServerResources = Slipe.Server.Resources
end)
System.namespace("Slipe.Server.Game.Events", function (namespace)
  namespace.class("OnPreStartEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, resource)
      this.Resource = SlipeServerResources.Resource.Get1(resource)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Resource", 0x6, out.Slipe.Server.Resources.Resource }
          },
          methods = {
            { ".ctor", 0x104, nil, out.Slipe.MtaDefinitions.MtaResource }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
