-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Sounds", function (namespace)
  -- <summary>
  -- Represents different sound containers
  -- </summary>
  namespace.enum("SoundContainer", function ()
    return {
      feet = 0,
      genrl = 1,
      pain_a = 2,
      script = 3,
      spc_ea = 4,
      spc_fa = 5,
      spc_na = 6,
      spc_pa = 7
    }
  end)

  -- <summary>
  -- Represents different radio stations
  -- </summary>
  namespace.enum("RadioStation", function ()
    return {
      RadioOff = 0,
      PlaybackFM = 1,
      KRose = 2,
      KDST = 3,
      BounceFM = 4,
      SFUR = 5,
      RadioLosSantos = 6,
      RadioX = 7,
      CSR1039 = 8,
      KJahWest = 9,
      MasterSounds983 = 10,
      WCTR = 11,
      UserTrackPlayer = 12
    }
  end)

  -- <summary>
  -- Represents interal GTA radio stations that are not the common ones
  -- </summary>
  namespace.enum("ExtraStations", function ()
    return {
      Adverts = 0,
      Ambience = 1,
      Police = 2,
      Custscene = 3,
      Beats = 4
    }
  end)
end)
