-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Browsers.Events", function (namespace)
  namespace.class("OnNavigateEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, target, isBlocked)
      this.Url = System.cast(System.String, target)
      this.IsBlocked = System.cast(System.Boolean, isBlocked)
    end
    return {
      IsBlocked = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "IsBlocked", 0x6, System.Boolean },
            { "Url", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x204, nil, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
