-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Browsers.Events", function (namespace)
  namespace.class("OnResourceBlockedEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, url, domain, reason)
      this.Url = System.cast(System.String, url)
      this.Domain = System.cast(System.String, domain)
      this.Reason = System.cast(System.Int32, reason)
    end
    return {
      Reason = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Domain", 0x6, System.String },
            { "Reason", 0x6, System.Int32 },
            { "Url", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x304, nil, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
