-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Client.Browsers.Events", function (namespace)
  namespace.class("OnWhiteListChangeEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, list)
      this.ChangedDomains = SlipeMtaDefinitions.MtaShared.GetArrayFromTable(list, "System.String", T)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "ChangedDomains", 0x6, System.Array(System.String) }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
