-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Sounds.Events", function (namespace)
  namespace.class("OnBeatEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, t)
      this.Time = System.cast(System.Single, t)
    end
    return {
      Time = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Time", 0x6, System.Single }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
