-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Sounds.Events", function (namespace)
  namespace.class("OnMetaChangedEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, t)
      this.StreamTitle = System.cast(System.String, t)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "StreamTitle", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
