-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientEffects
local SlipeMtaDefinitions
local SlipeSharedElements
System.import(function (out)
  SlipeClientEffects = Slipe.Client.Effects
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Effects", function (namespace)
  -- <summary>
  -- Represents a positionable effect
  -- </summary>
  namespace.class("Effect", function (namespace)
    local getDensity, setDensity, getSpeed, setSpeed, __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeSharedElements.PhysicalElement.__ctor__(this, element)
    end
    -- <summary>
    -- Create an effect of a type
    -- </summary>
    __ctor2__ = function (this, type, position, rotation, drawDistance, enableSound)
      SlipeSharedElements.PhysicalElement.__ctor__(this, SlipeMtaDefinitions.MtaClient.CreateEffect(type:ToEnumString(SlipeClientEffects.EffectType), position.X, position.Y, position.Z, rotation.X, rotation.Y, rotation.Z, drawDistance, enableSound))
    end
    getDensity = function (this)
      return SlipeMtaDefinitions.MtaClient.GetEffectDensity(this.element)
    end
    setDensity = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetEffectDensity(this.element, value)
    end
    getSpeed = function (this)
      return SlipeMtaDefinitions.MtaClient.GetEffectSpeed(this.element)
    end
    setSpeed = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetEffectSpeed(this.element, value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.PhysicalElement
        }
      end,
      getDensity = getDensity,
      setDensity = setDensity,
      getSpeed = getSpeed,
      setSpeed = setSpeed,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Density", 0x106, System.Single, getDensity, setDensity },
            { "Speed", 0x106, System.Single, getSpeed, setSpeed }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x506, __ctor2__, System.Int32, System.Numerics.Vector3, System.Numerics.Vector3, System.Single, System.Boolean }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 30 --[[ElementType.Effect]]) }
        }
      end
    }
  end)
end)
