-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnDamageEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, loss)
      this.Loss = System.cast(System.Single, loss)
    end
    return {
      Loss = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Loss", 0x6, System.Single }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
