-- Generated by CSharp.lua Compiler
local System = System
local SlipeServerPeds
local SlipeSharedElements
System.import(function (out)
  SlipeServerPeds = Slipe.Server.Peds
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Server.Vehicles.Events", function (namespace)
  namespace.class("OnExitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, player, seat, jacker, forcedByScript)
      this.Player = SlipeSharedElements.ElementManager.getInstance():GetElement(player, SlipeServerPeds.Player)
      this.Seat = System.cast(System.Int32, seat)
      this.Jacker = SlipeSharedElements.ElementManager.getInstance():GetElement(jacker, SlipeServerPeds.Player)
      this.IsForced = System.cast(System.Boolean, forcedByScript)
    end
    return {
      Seat = 0,
      IsForced = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "IsForced", 0x6, System.Boolean },
            { "Jacker", 0x6, out.Slipe.Server.Peds.Player },
            { "Player", 0x6, out.Slipe.Server.Peds.Player },
            { "Seat", 0x6, System.Int32 }
          },
          methods = {
            { ".ctor", 0x404, nil, out.Slipe.MtaDefinitions.MtaElement, System.Object, out.Slipe.MtaDefinitions.MtaElement, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
