-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedUtilities
System.import(function (out)
  SlipeSharedUtilities = Slipe.Shared.Utilities
end)
System.namespace("Slipe.Client.IO.Events", function (namespace)
  namespace.class("OnChatMessageEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, text, r, g, b)
      this.Text = System.cast(System.String, text)
      this.Color = System.new(SlipeSharedUtilities.Color, 4, System.cast(System.Byte, r), System.cast(System.Byte, g), System.cast(System.Byte, b))
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Color", 0x6, out.Slipe.Shared.Utilities.Color },
            { "Text", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x404, nil, System.Object, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
