-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedIO
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedIO = Slipe.Shared.IO
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.IO.Events", function (namespace)
  namespace.class("OnDoubleClickEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, mouseButton, sx, sy, wx, wy, wz, clickedElement)
      this.WorldPosition = System.default(SystemNumerics.Vector3)
      this.ScreenPosition = System.default(SystemNumerics.Vector2)
      this.MouseButton = System.cast(System.Int32, System.Enum.Parse(System.typeof(SlipeSharedIO.MouseButton), System.cast(System.String, mouseButton), true))
      this.ClickedElement = SlipeSharedElements.ElementManager.getInstance():GetElement(clickedElement, SlipeSharedElements.PhysicalElement)
      this.WorldPosition = SystemNumerics.Vector3(System.cast(System.Single, wx), System.cast(System.Single, wy), System.cast(System.Single, wz))
      this.ScreenPosition = SystemNumerics.Vector2(System.cast(System.Single, sx), System.cast(System.Single, sy))
    end
    return {
      MouseButton = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "ClickedElement", 0x6, out.Slipe.Shared.Elements.PhysicalElement },
            { "MouseButton", 0x6, System.Int32 },
            { "ScreenPosition", 0x6, System.Numerics.Vector2 },
            { "WorldPosition", 0x6, System.Numerics.Vector3 }
          },
          methods = {
            { ".ctor", 0x704, nil, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
