-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiComboBoxItem", function (namespace)
    local __ctor__
    __ctor__ = function (this, box, parent)
      (System.as(parent, SlipeClientGui.ComboBox)):AddItem(System.cast(System.String, box:getContent()))
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, nil, System.Windows.Controls.ComboBoxItem, out.Slipe.Client.Gui.GuiElement }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
