-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local SystemNumerics
local WpfRendererCegui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  SystemNumerics = System.Numerics
  WpfRendererCegui = WpfRenderer.Cegui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiEdit", function (namespace)
    local UpdateContent, __ctor1__, __ctor2__
    __ctor1__ = function (this, block, parent)
      SlipeClientGui.Edit.__ctor__[2](this, SystemNumerics.Vector2(System.ToSingle(block:getMargin():getLeft()), System.ToSingle(block:getMargin():getTop())), SystemNumerics.Vector2(System.ToSingle(block:getWidth()), System.ToSingle(block:getHeight())), block:getText(), false, parent, false, 128)
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, block)

      this.OnChanged = this.OnChanged + function (source, args)
        block:setText(this:getContent())
      end

      block:addTextChanged(System.fn(this, UpdateContent))
    end
    __ctor2__ = function (this, block, parent)
      SlipeClientGui.Edit.__ctor__[2](this, SystemNumerics.Vector2(System.ToSingle(block:getMargin():getLeft()), System.ToSingle(block:getMargin():getTop())), SystemNumerics.Vector2(System.ToSingle(block:getWidth()), System.ToSingle(block:getHeight())), block:getPassword(), false, parent, false, 128)
      this:setMasked(true)
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, block)

      this.OnChanged = this.OnChanged + function (source, args)
        block:setPassword(this:getContent())
      end

      block:addPasswordChanged(System.fn(this, UpdateContent))
    end
    UpdateContent = function (this, content)
      if this:getContent() ~= content then
        this:setContent(content)
      end
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.Edit
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, __ctor1__, System.Windows.Controls.TextBox, out.Slipe.Client.Gui.GuiElement },
            { ".ctor", 0x206, __ctor2__, System.Windows.Controls.PasswordBox, out.Slipe.Client.Gui.GuiElement },
            { "UpdateContent", 0x101, UpdateContent, System.String }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
