-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientGui
local WpfRendererCegui
System.import(function (out)
  SlipeClientGui = Slipe.Client.Gui
  WpfRendererCegui = WpfRenderer.Cegui
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiTab", function (namespace)
    local __ctor__
    __ctor__ = function (this, item, parent)
      SlipeClientGui.Tab.__ctor__[2](this, System.cast(System.String, item:getHeader()), System.cast(SlipeClientGui.TabPanel, parent))
      WpfRendererCegui.GuiWpfHelper.AttachHandlers(this, item)

      WpfRendererCegui.GuiWpfHelper.CreateChildren(this, item)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Client.Gui.Tab
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, nil, System.Windows.Controls.TabItem, out.Slipe.Client.Gui.GuiElement }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
