-- Generated by CSharp.lua Compiler
local System = System
local WpfRendererCeguiElements
System.import(function (out)
  WpfRendererCeguiElements = WpfRenderer.Cegui.Elements
end)
System.namespace("WpfRenderer.Cegui.Elements", function (namespace)
  namespace.class("WpfGuiGrid", function (namespace)
    local __ctor__
    __ctor__ = function (this, window, parent)
      WpfRendererCeguiElements.WpfGuiDummy.__ctor__(this, window, parent)
    end
    return {
      __inherits__ = function (out)
        return {
          out.WpfRenderer.Cegui.Elements.WpfGuiDummy
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x206, nil, System.Windows.Controls.Grid, out.Slipe.Client.Gui.GuiElement }
          },
          class = { 0x4 }
        }
      end
    }
  end)
end)
