-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeServerDisplays
local SlipeSharedUtilities
local SystemNumerics
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeServerDisplays = Slipe.Server.Displays
  SlipeSharedUtilities = Slipe.Shared.Utilities
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Server.Displays", function (namespace)
  -- <summary>
  -- Represents a text label visible on a display
  -- </summary>
  namespace.class("Item", function (namespace)
    local getVisible, setVisible, getColor, setColor, getPosition, setPosition, getPriority, setPriority, 
    getScale, setScale, getContent, setContent, Destroy, __ctor1__, __ctor2__, __ctor3__, 
    __ctor4__
    -- <summary>
    -- Create a new text item
    -- </summary>
    __ctor1__ = function (this, display, content, position, priority, color, scale, alignX, alignY, shadowAlpha)
      this.Display = display
      this.ItemElement = SlipeMtaDefinitions.MtaServer.TextCreateTextItem(content, position.X, position.Y, priority:ToEnumString(SlipeServerDisplays.Priority):ToLower(), color:getR(), color:getG(), color:getB(), color:getA(), scale, alignX:ToEnumString(SlipeServerDisplays.HorizontalAlignment):ToLower(), alignY:ToEnumString(SlipeServerDisplays.VerticalAlignment):ToLower(), shadowAlpha)
      SlipeMtaDefinitions.MtaServer.TextDisplayAddText(display.DisplayElement, this.ItemElement)
      this.visible = true
    end
    -- <summary>
    -- Create a new text item
    -- </summary>
    __ctor2__ = function (this, display, content, position, priority, color, scale)
      __ctor1__(this, display, content, position:__clone__(), priority, color, scale, 0 --[[HorizontalAlignment.Left]], 0 --[[VerticalAlignment.Top]], 0)
    end
    -- <summary>
    -- Create a new text item
    -- </summary>
    __ctor3__ = function (this, display, content, position, priority)
      __ctor2__(this, display, content, position:__clone__(), priority, SlipeSharedUtilities.Color.getWhite(), 1)
    end
    -- <summary>
    -- Create a new text item
    -- </summary>
    __ctor4__ = function (this, display, content, position)
      __ctor3__(this, display, content, position:__clone__(), 1 --[[Priority.Medium]])
    end
    getVisible = function (this)
      return this.visible
    end
    setVisible = function (this, value)
      this.visible = value
      if this.visible then
        SlipeMtaDefinitions.MtaServer.TextDisplayAddText(this.Display.DisplayElement, this.ItemElement)
      else
        SlipeMtaDefinitions.MtaServer.TextDisplayRemoveText(this.Display.DisplayElement, this.ItemElement)
      end
    end
    getColor = function (this)
      local c = SlipeMtaDefinitions.MtaServer.TextItemGetColor(this.ItemElement)
      return System.new(SlipeSharedUtilities.Color, 3, System.toByte(c[1]), System.toByte(c[2]), System.toByte(c[3]), System.toByte(c[4]))
    end
    setColor = function (this, value)
      SlipeMtaDefinitions.MtaServer.TextItemSetColor(this.ItemElement, value:getR(), value:getG(), value:getB(), value:getA())
    end
    getPosition = function (this)
      local r = SlipeMtaDefinitions.MtaServer.TextItemGetPosition(this.ItemElement)
      return SystemNumerics.Vector2(r[1], r[2])
    end
    setPosition = function (this, value)
      SlipeMtaDefinitions.MtaServer.TextItemSetPosition(this.ItemElement, value.X, value.Y)
    end
    getPriority = function (this)
      return SlipeMtaDefinitions.MtaServer.TextItemGetPriority(this.ItemElement)
    end
    setPriority = function (this, value)
      SlipeMtaDefinitions.MtaServer.TextItemSetPriority(this.ItemElement, value:ToEnumString(SlipeServerDisplays.Priority):ToLower())
    end
    getScale = function (this)
      return SlipeMtaDefinitions.MtaServer.TextItemGetScale(this.ItemElement)
    end
    setScale = function (this, value)
      SlipeMtaDefinitions.MtaServer.TextItemSetScale(this.ItemElement, value)
    end
    getContent = function (this)
      return SlipeMtaDefinitions.MtaServer.TextItemGetText(this.ItemElement)
    end
    setContent = function (this, value)
      SlipeMtaDefinitions.MtaServer.TextItemSetText(this.ItemElement, value)
    end
    Destroy = function (this)
      return SlipeMtaDefinitions.MtaServer.TextDestroyTextItem(this.ItemElement)
    end
    return {
      visible = false,
      getVisible = getVisible,
      setVisible = setVisible,
      getColor = getColor,
      setColor = setColor,
      getPosition = getPosition,
      setPosition = setPosition,
      getPriority = getPriority,
      setPriority = setPriority,
      getScale = getScale,
      setScale = setScale,
      getContent = getContent,
      setContent = setContent,
      Destroy = Destroy,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__,
        __ctor4__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Color", 0x106, out.Slipe.Shared.Utilities.Color, getColor, setColor },
            { "Content", 0x106, System.String, getContent, setContent },
            { "Display", 0x6, out.Slipe.Server.Displays.Display },
            { "ItemElement", 0x6, out.Slipe.MtaDefinitions.MtaElement },
            { "Position", 0x106, System.Numerics.Vector2, getPosition, setPosition },
            { "Priority", 0x106, System.Int32, getPriority, setPriority },
            { "Scale", 0x106, System.Single, getScale, setScale },
            { "Visible", 0x106, System.Boolean, getVisible, setVisible }
          },
          fields = {
            { "visible", 0x1, System.Boolean }
          },
          methods = {
            { ".ctor", 0x906, __ctor1__, out.Slipe.Server.Displays.Display, System.String, System.Numerics.Vector2, System.Int32, out.Slipe.Shared.Utilities.Color, System.Single, System.Int32, System.Int32, System.Int32 },
            { ".ctor", 0x606, __ctor2__, out.Slipe.Server.Displays.Display, System.String, System.Numerics.Vector2, System.Int32, out.Slipe.Shared.Utilities.Color, System.Single },
            { ".ctor", 0x406, __ctor3__, out.Slipe.Server.Displays.Display, System.String, System.Numerics.Vector2, System.Int32 },
            { ".ctor", 0x306, __ctor4__, out.Slipe.Server.Displays.Display, System.String, System.Numerics.Vector2 },
            { "Destroy", 0x86, Destroy, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
