-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedGameWorld
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedGameWorld = Slipe.Shared.GameWorld
end)
System.namespace("Slipe.Client.GameWorld", function (namespace)
  -- <summary>
  -- Class representing an object in the GTA world
  -- </summary>
  namespace.class("WorldObject", function (namespace)
    local getMass, setMass, getBreakable, setBreakable, setRespawns, Break, Respawn, class, 
    __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this, element)
      SlipeSharedGameWorld.SharedWorldObject.__ctor__[1](this, element)
    end
    -- <summary>
    -- Create a world object at a specific position
    -- </summary>
    __ctor2__ = function (this, model, position)
      SlipeSharedGameWorld.SharedWorldObject.__ctor__[3](this, model, position:__clone__())
    end
    -- <summary>
    -- Create a world object using all parameters
    -- </summary>
    __ctor3__ = function (this, model, position, rotation, isLowLOD)
      SlipeSharedGameWorld.SharedWorldObject.__ctor__[2](this, model, position:__clone__(), rotation:__clone__(), isLowLOD)
    end
    getMass = function (this)
      return SlipeMtaDefinitions.MtaClient.GetObjectMass(this.element)
    end
    setMass = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetObjectMass(this.element, value)
    end
    getBreakable = function (this)
      return SlipeMtaDefinitions.MtaClient.IsObjectBreakable(this.element)
    end
    setBreakable = function (this, value)
      SlipeMtaDefinitions.MtaClient.SetObjectBreakable(this.element, value)
    end
    setRespawns = function (this, value)
      SlipeMtaDefinitions.MtaClient.ToggleObjectRespawn(this.element, value)
    end
    -- <summary>
    -- Break this object
    -- </summary>
    Break = function (this)
      SlipeMtaDefinitions.MtaClient.BreakObject(this.element)
    end
    -- <summary>
    -- Respawn this object
    -- </summary>
    Respawn = function (this)
      SlipeMtaDefinitions.MtaClient.RespawnObject(this.element)
    end
    class = {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.GameWorld.SharedWorldObject
        }
      end,
      getMass = getMass,
      setMass = setMass,
      getBreakable = getBreakable,
      setBreakable = setBreakable,
      setRespawns = setRespawns,
      Break = Break,
      Respawn = Respawn,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Breakable", 0x106, System.Boolean, getBreakable, setBreakable },
            { "Mass", 0x106, System.Single, getMass, setMass },
            { "Respawns", 0x306, System.Boolean, setRespawns }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x206, __ctor2__, System.Int32, System.Numerics.Vector3 },
            { ".ctor", 0x406, __ctor3__, System.Int32, System.Numerics.Vector3, System.Numerics.Vector3, System.Boolean },
            { "Break", 0x6, Break },
            { "Respawn", 0x6, Respawn }
          },
          events = {
            { "OnBreak", 0x6, System.Delegate(class, out.Slipe.Client.GameWorld.Events.OnBreakEventArgs, System.Void) },
            { "OnDamage", 0x6, System.Delegate(class, out.Slipe.Client.GameWorld.Events.OnDamageEventArgs, System.Void) },
            { "OnExplosion", 0x6, System.Delegate(class, out.Slipe.Client.Elements.Events.OnExplosionEventArgs, System.Void) }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 4 --[[ElementType.Object]]) }
        }
      end
    }
    return class
  end)
end)
