-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.GameWorld", function (namespace)
  -- <summary>
  -- Represents different properties of setWorldSpecialPropertyEnabled
  -- </summary>
  namespace.enum("WorldSpecialProperty", function ()
    return {
      HoverCars = 0,
      AirCars = 1,
      ExtraBunny = 2,
      ExtraJump = 3,
      RandomFoliage = 4,
      SniperMoon = 5,
      ExtraAiResistance = 6,
      UnderWorldWarp = 7
    }
  end)
end)
