-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Client.Vehicles.Events", function (namespace)
  namespace.class("OnCollisionEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, hitElement, force, bodyPart, cx, cy, cz, nx, ny, nz, model)
      this.Position = System.default(SystemNumerics.Vector3)
      this.Normal = System.default(SystemNumerics.Vector3)
      this.Element = SlipeSharedElements.ElementManager.getInstance():GetElement(hitElement, SlipeSharedElements.PhysicalElement)
      this.Force = System.cast(System.Single, force)
      this.Part = System.cast(System.Int32, bodyPart)
      this.Position = SystemNumerics.Vector3(System.cast(System.Single, cx), System.cast(System.Single, cy), System.cast(System.Single, cz))
      this.Normal = SystemNumerics.Vector3(System.cast(System.Single, nx), System.cast(System.Single, ny), System.cast(System.Single, nz))
      this.Model = System.cast(System.Int32, model)
    end
    return {
      Force = 0,
      Part = 0,
      Model = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Element", 0x6, out.Slipe.Shared.Elements.PhysicalElement },
            { "Force", 0x6, System.Single },
            { "Model", 0x6, System.Int32 },
            { "Normal", 0x6, System.Numerics.Vector3 },
            { "Part", 0x6, System.Int32 },
            { "Position", 0x6, System.Numerics.Vector3 }
          },
          methods = {
            { ".ctor", 0xA04, nil, out.Slipe.MtaDefinitions.MtaElement, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
