-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientPeds
local SlipeSharedElements
System.import(function (out)
  SlipeClientPeds = Slipe.Client.Peds
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Vehicles.Events", function (namespace)
  namespace.class("OnPedHitEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, ped)
      this.Ped = SlipeSharedElements.ElementManager.getInstance():GetElement(ped, SlipeClientPeds.Ped)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Ped", 0x6, out.Slipe.Client.Peds.Ped }
          },
          methods = {
            { ".ctor", 0x104, nil, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
