-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Vehicles.Events", function (namespace)
  namespace.class("OnRespawnEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, b)
      this.Exploded = System.cast(System.Boolean, b)
    end
    return {
      Exploded = false,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Exploded", 0x6, System.Boolean }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
