-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedWeapons
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedWeapons = Slipe.Shared.Weapons
end)
System.namespace("Slipe.Server.Weapons", function (namespace)
  namespace.class("WeaponModel", function (namespace)
    local getJetPackEnabled, setJetPackEnabled, SetProperty, SetProperty1, __ctor1__, __ctor2__
    -- <summary>
    -- Get a weapon model from the weapon name
    -- </summary>
    __ctor1__ = function (this, name)
      SlipeSharedWeapons.SharedWeaponModel.__ctor__[2](this, name)
    end
    -- <summary>
    -- Get a weapon model from the weapon id
    -- </summary>
    __ctor2__ = function (this, id)
      SlipeSharedWeapons.SharedWeaponModel.__ctor__[1](this, id)
    end
    getJetPackEnabled = function (this)
      return SlipeMtaDefinitions.MtaServer.GetJetpackWeaponEnabled(this:getName())
    end
    setJetPackEnabled = function (this, value)
      SlipeMtaDefinitions.MtaServer.SetJetpackWeaponEnabled(this:getName(), value)
    end
    -- <summary>
    -- Sets the value of a property of this mode
    -- </summary>
    -- <param name="property"></param>
    -- <param name="value"></param>
    -- <returns></returns>
    SetProperty = function (this, skill, property, value)
      return SlipeMtaDefinitions.MtaShared.SetWeaponProperty(this.ID, skill:ToEnumString(SlipeSharedWeapons.WeaponSkill):ToLower(), property:ToEnumString(SlipeSharedWeapons.WeaponProperty):ToLower(), value)
    end
    -- <summary>
    -- Sets the value of a property of this mode
    -- </summary>
    -- <param name="property"></param>
    -- <param name="value"></param>
    -- <returns></returns>
    SetProperty1 = function (this, skill, property, value)
      return SlipeMtaDefinitions.MtaShared.SetWeaponProperty(this.ID, skill:ToEnumString(SlipeSharedWeapons.WeaponSkill):ToLower(), property:ToEnumString(SlipeSharedWeapons.WeaponProperty):ToLower(), value)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Weapons.SharedWeaponModel
        }
      end,
      getJetPackEnabled = getJetPackEnabled,
      setJetPackEnabled = setJetPackEnabled,
      SetProperty = SetProperty,
      SetProperty1 = SetProperty1,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "JetPackEnabled", 0x106, System.Boolean, getJetPackEnabled, setJetPackEnabled }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, System.String },
            { ".ctor", 0x106, __ctor2__, System.Int32 },
            { "SetProperty", 0x386, SetProperty, System.Int32, System.Int32, System.Single, System.Boolean },
            { "SetProperty", 0x386, SetProperty1, System.Int32, System.Int32, System.Int32, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
