-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
local SlipeSharedPeds
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedPeds = Slipe.Shared.Peds
end)
System.namespace("Slipe.Shared.Elements.Events", function (namespace)
  namespace.class("OnStopSyncEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, oldSyncer)
      this.OldSyncer = SlipeSharedElements.ElementManager.getInstance():GetElement(oldSyncer, SlipeSharedPeds.SharedPed)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "OldSyncer", 0x6, out.Slipe.Shared.Peds.SharedPed }
          },
          methods = {
            { ".ctor", 0x104, nil, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
