-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.IO", function (namespace)
  namespace.enum("DebugMessageLevel", function ()
    return {
      Custom = 0,
      Error = 1,
      Warning = 2,
      Information = 3
    }
  end)
end)
