-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.GameWorld.Events", function (namespace)
  namespace.class("OnDamageEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, target)
      this.Attacker = SlipeSharedElements.ElementManager.getInstance():GetElement(target, SlipeSharedElements.PhysicalElement)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Attacker", 0x6, out.Slipe.Shared.Elements.PhysicalElement }
          },
          methods = {
            { ".ctor", 0x104, nil, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
