-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientElements
local SlipeClientRpc
local SlipeMtaDefinitions
local SlipeSharedElements
local SlipeSharedRpc
local ListRegisteredRpc
local DictStringListRegisteredRpc
System.import(function (out)
  SlipeClientElements = Slipe.Client.Elements
  SlipeClientRpc = Slipe.Client.Rpc
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedRpc = Slipe.Shared.Rpc
  ListRegisteredRpc = System.List(SlipeClientRpc.RegisteredRpc)
  DictStringListRegisteredRpc = System.Dictionary(System.String, ListRegisteredRpc)
end)
System.namespace("Slipe.Client.Rpc", function (namespace)
  namespace.class("RpcManager", function (namespace)
    local instance, getInstance, RegisterRPC, TriggerRPC, TriggerLatentRPC, TriggerAsyncRpc, RegisterAsyncRPC, class, 
    __ctor__
    __ctor__ = function (this)
      this.asyncRpcIndex = 0
      this.registeredRPCs = DictStringListRegisteredRpc()
      this.registeredAsyncRPCs = DictStringListRegisteredRpc()

      SlipeClientElements.RootElement.OnMiscelaniousEvent = SlipeClientElements.RootElement.OnMiscelaniousEvent + function (eventName, source, p1, p2, p3, p4, p5, p6, p7, p8)
        if this.registeredRPCs:ContainsKey(eventName) then
          local registeredRpcs = this.registeredRPCs:get(eventName)

          for _, registeredRpc in System.each(registeredRpcs) do
            local method = registeredRpc.callback

            local rpc = System.cast(SlipeSharedRpc.IRpc, System.Activator.CreateInstance(registeredRpc.type))
            rpc:Parse(p1)
            method(rpc)
          end
        elseif this.registeredAsyncRPCs:ContainsKey(eventName) then
          local registeredRpcs = this.registeredAsyncRPCs:get(eventName)

          for _, registeredRpc in System.each(registeredRpcs) do
            local method = registeredRpc.callback

            local asyncRpc = System.Activator.CreateInstance(SlipeSharedRpc.AsyncRpc)
            asyncRpc:Parse(p1)

            method(asyncRpc)
          end
        end
      end
    end
    getInstance = function ()
      if instance == nil then
        instance = class()
      end
      return instance
    end
    -- <summary>
    -- Register an RPC
    -- </summary>
    RegisterRPC = function (this, key, callback, CallbackType)
      if not this.registeredRPCs:ContainsKey(key) then
        this.registeredRPCs:set(key, ListRegisteredRpc())
        SlipeMtaDefinitions.MtaShared.AddEvent(key, true)
        SlipeSharedElements.Element.getRoot():ListenForEvent(key, true, "normal")
      end
      this.registeredRPCs:get(key):Add(System.new(SlipeClientRpc.RegisteredRpc, 2, function (parameters)
        callback(System.cast(CallbackType, parameters), CallbackType)
      end, System.typeof(CallbackType)))
    end
    -- <summary>
    -- Trigger an RPC
    -- </summary>
    TriggerRPC = function (this, key, argument)
      SlipeMtaDefinitions.MtaClient.TriggerServerEvent(key, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    -- <summary>
    -- Trigger an RPC with limited bandwidth
    -- </summary>
    TriggerLatentRPC = function (this, key, bandwidth, argument, persists)
      SlipeMtaDefinitions.MtaClient.TriggerLatentServerEvent(key, bandwidth, persists, SlipeSharedElements.Element.getRoot():getMTAElement(), argument)
    end
    TriggerAsyncRpc = function (this, key, argument, TResponseRpc)
      local tickCount = SlipeMtaDefinitions.MtaShared.GetTickCount()
      local responseKey = "response-" .. key

      local task = nil
      local callback = nil

      this.asyncRpcIndex = this.asyncRpcIndex + 1
      local identifier = this.asyncRpcIndex .. ""

      local asyncCallback
      callback = function(parameters)
          if (parameters.Identifier == identifier) then
              local asyncRpc = System.cast(SlipeSharedRpc.AsyncRpc, parameters)
              local arguments = System.cast(TResponseRpc, System.Activator.CreateInstance(System.typeof(TResponseRpc)))
              arguments:Parse(asyncRpc.Rpc)
              asyncCallback(arguments)
          end
      end
      task, asyncCallback = System.Task.Callback(function(responseRpc)
          this.registeredRPCs:get(responseKey):Remove(callback)
          return responseRpc;
      end)

      RegisterRPC(this, responseKey, callback, SlipeSharedRpc.AsyncRpc)

      SlipeMtaDefinitions.MtaClient.TriggerServerEvent(key, SlipeSharedElements.Element.getRoot():getMTAElement(), System.new(SlipeSharedRpc.AsyncRpc, 2, identifier, argument))

      return task
    end
    -- <summary>
    -- Register an async RPC
    -- </summary>
    RegisterAsyncRPC = function (this, key, callback, ResponseRpc, RequestRpc)
      if not this.registeredAsyncRPCs:ContainsKey(key) then
        this.registeredAsyncRPCs:set(key, ListRegisteredRpc())
        SlipeMtaDefinitions.MtaShared.AddEvent(key, true)
        SlipeSharedElements.Element.getRoot():ListenForEvent(key, true, "normal")
      end

      local responseKey = "response-" .. key
      this.registeredAsyncRPCs:get(key):Add(System.new(SlipeClientRpc.RegisteredRpc, 2, function (parameters)
        local asyncRpc = System.cast(SlipeSharedRpc.AsyncRpc, parameters)
        local arguments = System.cast(RequestRpc, System.Activator.CreateInstance(System.typeof(RequestRpc)))
        arguments:Parse(asyncRpc.Rpc)

        local result = callback(arguments, RequestRpc, ResponseRpc)
        TriggerRPC(this, responseKey, System.new(SlipeSharedRpc.AsyncRpc, 2, asyncRpc.Identifier, result))
      end, System.typeof(SlipeSharedRpc.AsyncRpc)))
    end
    class = {
      getInstance = getInstance,
      asyncRpcIndex = 0,
      RegisterRPC = RegisterRPC,
      TriggerRPC = TriggerRPC,
      TriggerLatentRPC = TriggerLatentRPC,
      TriggerAsyncRpc = TriggerAsyncRpc,
      RegisterAsyncRPC = RegisterAsyncRPC,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          fields = {
            { "asyncRpcIndex", 0x1, System.Int32 },
            { "instance", 0x9, class },
            { "registeredAsyncRPCs", 0x1, System.Dictionary(System.String, System.List(out.Slipe.Client.Rpc.RegisteredRpc)) },
            { "registeredRPCs", 0x1, System.Dictionary(System.String, System.List(out.Slipe.Client.Rpc.RegisteredRpc)) }
          },
          properties = {
            { "Instance", 0x20E, class, getInstance }
          },
          methods = {
            { ".ctor", 0x1, nil },
            { "RegisterAsyncRPC", 0x20206, RegisterAsyncRPC, function (ResponseRpc, RequestRpc) return System.String, System.Delegate(RequestRpc, ResponseRpc) end },
            { "RegisterRPC", 0x10206, RegisterRPC, function (CallbackType) return System.String, System.Delegate(CallbackType, System.Void) end },
            { "TriggerAsyncRpc", 0x10286, TriggerAsyncRpc, function (TResponseRpc) return System.String, out.Slipe.Shared.Rpc.IRpc, System.Task end },
            { "TriggerLatentRPC", 0x406, TriggerLatentRPC, System.String, System.Int32, out.Slipe.Shared.Rpc.IRpc, System.Boolean },
            { "TriggerRPC", 0x206, TriggerRPC, System.String, out.Slipe.Shared.Rpc.IRpc }
          },
          class = { 0x6 }
        }
      end
    }
    return class
  end)

  namespace.struct("RegisteredRpc", function (namespace)
    local __ctor1__, __ctor2__
    __ctor1__ = function (this)
    end
    __ctor2__ = function (this, callback, type)
      this.callback = callback
      this.type = type
    end
    return {
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          fields = {
            { "callback", 0x6, System.Delegate(out.Slipe.Shared.Rpc.IRpc, System.Void) },
            { "type", 0x6, System.Type }
          },
          methods = {
            { ".ctor", 0x206, __ctor2__, System.Delegate(out.Slipe.Shared.Rpc.IRpc, System.Void), System.Type }
          }
        }
      end
    }
  end)
end)
