-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Peds", function (namespace)
  -- <summary>
  -- Represents a type of damage a player can receive
  -- </summary>
  namespace.enum("DamageType", function ()
    return {
      Fist = 0,
      Brassknuckle = 1,
      Golfclub = 2,
      Nightstick = 3,
      Knife = 4,
      Bat = 5,
      Shovel = 6,
      Poolstic = 7,
      Katan = 8,
      Chainsaw = 9,
      Dildo1 = 10,
      Dildo2 = 11,
      Vibrator = 12,
      Flower = 14,
      Cane = 15,
      Grenade = 16,
      Teargas = 17,
      Molotov = 18,
      Rocket = 19,
      Colt45 = 22,
      Silenced = 23,
      Deagle = 24,
      Shotgun = 25,
      Sawedoff = 26,
      CombatShotgun = 27,
      Uzi = 28,
      Mp5 = 29,
      Ak47 = 30,
      M4 = 31,
      Tec9 = 32,
      Rifle = 33,
      Sniper = 34,
      RocketLauncer = 35,
      RocketLauncherHs = 36,
      Burnt = 37,
      Minigun = 38,
      Satchel = 39,
      Bomb = 40,
      Spraycan = 41,
      FireExtinguisher = 42,
      Camera = 43,
      Nightvision = 44,
      Infrared = 45,
      Parachute = 46,
      Rammed = 49,
      Ranover = 50,
      Explosion = 51,
      Driveby = 52,
      Drowned = 53,
      Fall = 54,
      TankGrenade = 59,
      VehicleBlown = 63
    }
  end)
end)
