-- Generated by CSharp.lua Compiler
local System = System
local SlipeClientPeds
local SlipeSharedElements
local SlipeSharedWeapons
System.import(function (out)
  SlipeClientPeds = Slipe.Client.Peds
  SlipeSharedElements = Slipe.Shared.Elements
  SlipeSharedWeapons = Slipe.Shared.Weapons
end)
System.namespace("Slipe.Client.Peds.Events", function (namespace)
  namespace.class("OnChokeEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, model, ped)
      this.WeaponModel = SlipeSharedWeapons.SharedWeaponModel(System.cast(System.Int32, model))
      this.ResponsiblePed = SlipeSharedElements.ElementManager.getInstance():GetElement(ped, SlipeClientPeds.Ped)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "ResponsiblePed", 0x1, out.Slipe.Client.Peds.Ped },
            { "WeaponModel", 0x1, out.Slipe.Shared.Weapons.SharedWeaponModel }
          },
          methods = {
            { ".ctor", 0x204, nil, System.Object, out.Slipe.MtaDefinitions.MtaElement }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
