-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Peds.Events", function (namespace)
  namespace.class("OnConsoleEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, message)
      this.Message = System.cast(System.String, message)
    end
    return {
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Message", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x104, nil, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
