-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedElements
System.import(function (out)
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Peds.Events", function (namespace)
  namespace.class("OnDamageEventArgs", function (namespace)
    local __ctor__
    __ctor__ = function (this, attacker, damageType, bodyPart, loss)
      this.Attacker = SlipeSharedElements.ElementManager.getInstance():GetElement(attacker, SlipeSharedElements.PhysicalElement)
      this.DamageType = System.cast(System.Int32, damageType)
      this.BodyPart = System.cast(System.Int32, bodyPart)
      this.Loss = System.cast(System.Single, loss)
    end
    return {
      DamageType = 0,
      BodyPart = 0,
      Loss = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Attacker", 0x6, out.Slipe.Shared.Elements.PhysicalElement },
            { "BodyPart", 0x6, System.Int32 },
            { "DamageType", 0x6, System.Int32 },
            { "Loss", 0x6, System.Single }
          },
          methods = {
            { ".ctor", 0x404, nil, out.Slipe.MtaDefinitions.MtaElement, System.Object, System.Object, System.Object }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
