-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.GameWorld", function (namespace)
  -- <summary>
  -- Reprents different garages around the world
  -- </summary>
  namespace.enum("GarageLocation", function ()
    return {
      Commerce = 0,
      LspdImpound = 1,
      LosDeperados = 2,
      EightballAutos = 3,
      CesarVialpando = 4,
      PropertyElCorona = 5,
      LsBurglaryGarage = 6,
      LowriderTuning = 7,
      PaynSprayIdlewood = 8,
      PropertyGanton = 9,
      TransfenderTemple = 10,
      PaynSprayTemple = 11,
      PaynSpraySantaMaria = 12,
      PropertySantaMaria = 13,
      PropertyMulholland = 14,
      WheelArchAngelsOceanFlats = 15,
      TBoneMendez = 16,
      PropertyGarageHashbury = 17,
      TransfenderDoherty = 18,
      PaynSprayDowntown = 19,
      SfBurglaryGarage = 20,
      PropertyDoherty = 21,
      MissionDoherty = 22,
      Ranfali = 23,
      MichellesPaynSpray = 24,
      PropertyCaltonHeights = 25,
      SfpdImpound = 26,
      PaynSprayJuniperHollow = 27,
      PropertyParadiso = 28,
      LvpdImpound = 29,
      AirportHangarLv = 30,
      LvBurglary = 31,
      PaynSprayRoyalCasino = 32,
      TransfenderComeaLot = 33,
      PropertyRockshoreWest = 34,
      WeldingWeddingBomb = 35,
      PaynSprayRedsandsEast = 36,
      PropertyRedsandsWest = 37,
      PropertyPricklepine = 38,
      PropertyWhitewoodEstates = 39,
      PaynSprayElQuebrados = 40,
      PaynSprayFortCarson = 41,
      PropertyFortCarson = 42,
      PropertyVerdantMeadows = 43,
      Interdiction = 44,
      AirportHangerVerdantMeadows = 45,
      PunctureWounds = 46,
      PaynSprayDillimore = 47,
      PropertyPalominoCreek = 48,
      PropertyDillimore = 49
    }
  end)
end)
