-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
local SystemNumerics
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
  SystemNumerics = System.Numerics
end)
System.namespace("Slipe.Shared.GameWorld", function (namespace)
  -- <summary>
  -- Class used to create bodies of water on the map
  -- </summary>
  namespace.class("SharedWater", function (namespace)
    local setLevel, SetVertexPosition, GetVertexPosition, __ctor1__, __ctor2__, __ctor3__
    -- <summary>
    -- Create water from an MTA water element
    -- </summary>
    __ctor1__ = function (this, element)
      SlipeSharedElements.PhysicalElement.__ctor__(this, element)
    end
    -- <summary>
    -- Creates a body of water from 4 corners. Order: SouthWest -> SouthEast -> NorthWest -> NorthEast
    -- </summary>
    __ctor2__ = function (this, southWest, southEast, northWest, northEast, shallow)
      __ctor1__(this, SlipeMtaDefinitions.MtaShared.CreateWater(southWest.X, southWest.Y, southWest.Z, southEast.X, southEast.Y, southEast.Z, northWest.X, northWest.Y, northWest.Z, northEast.X, northEast.Y, northEast.Z, shallow))
    end
    -- <summary>
    -- Creates a body of water from 3 corners. Order: SouthWest -> SouthEast -> NorthWest
    -- </summary>
    __ctor3__ = function (this, southWest, southEast, northWest, shallow)
      __ctor1__(this, SlipeMtaDefinitions.MtaShared.CreateWater(southWest.X, southWest.Y, southWest.Z, southEast.X, southEast.Y, southEast.Z, northWest.X, northWest.Y, northWest.Z, shallow))
    end
    setLevel = function (this, value)
      SlipeMtaDefinitions.MtaShared.SetWaterLevel(this.element, value)
    end
    -- <summary>
    -- Sets the water position of a specific index follow the order SW, SE, NW, NE
    -- </summary>
    SetVertexPosition = function (this, vertexIndex, position)
      return SlipeMtaDefinitions.MtaShared.SetWaterVertexPosition(this.element, vertexIndex, System.ToInt32(position.X), System.ToInt32(position.Y), position.Z)
    end
    -- <summary>
    -- Gets the world position of a vertex (i.e. corner) of a water area. Follow the order SW, SE, NW, NE
    -- </summary>
    GetVertexPosition = function (this, vertexIndex)
      local result = SlipeMtaDefinitions.MtaShared.GetWaterVertexPosition(this.element, vertexIndex)
      return SystemNumerics.Vector3(result[1], result[2], result[3])
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.PhysicalElement
        }
      end,
      setLevel = setLevel,
      SetVertexPosition = SetVertexPosition,
      GetVertexPosition = GetVertexPosition,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          properties = {
            { "Level", 0x306, System.Single, setLevel }
          },
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x506, __ctor2__, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Boolean },
            { ".ctor", 0x406, __ctor3__, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Boolean },
            { "GetVertexPosition", 0x186, GetVertexPosition, System.Int32, System.Numerics.Vector3 },
            { "SetVertexPosition", 0x286, SetVertexPosition, System.Int32, System.Numerics.Vector3, System.Boolean }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
