-- Generated by CSharp.lua Compiler
local System = System
local SlipeSharedGameWorld
System.import(function (out)
  SlipeSharedGameWorld = Slipe.Shared.GameWorld
end)
System.namespace("Slipe.Server.GameWorld", function (namespace)
  -- <summary>
  -- Class used to create bodies of water on the map
  -- </summary>
  namespace.class("Water", function (namespace)
    local __ctor1__, __ctor2__, __ctor3__
    __ctor1__ = function (this, element)
      SlipeSharedGameWorld.SharedWater.__ctor__[1](this, element)
    end
    -- <summary>
    -- Creates a body of water from 4 corners.
    -- </summary>
    __ctor2__ = function (this, corner1, corner2, corner3, corner4, shallow)
      SlipeSharedGameWorld.SharedWater.__ctor__[2](this, corner1:__clone__(), corner2:__clone__(), corner3:__clone__(), corner4:__clone__(), shallow)
    end
    -- <summary>
    -- Creates a body of water from 3 corners.
    -- </summary>
    __ctor3__ = function (this, corner1, corner2, corner3, shallow)
      SlipeSharedGameWorld.SharedWater.__ctor__[3](this, corner1:__clone__(), corner2:__clone__(), corner3:__clone__(), shallow)
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.GameWorld.SharedWater
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__,
        __ctor3__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x506, __ctor2__, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Boolean },
            { ".ctor", 0x406, __ctor3__, System.Numerics.Vector3, System.Numerics.Vector3, System.Numerics.Vector3, System.Boolean }
          },
          class = { 0x6, System.new(out.Slipe.Shared.Elements.DefaultElementClassAttribute, 2, 34 --[[ElementType.Water]]) }
        }
      end
    }
  end)
end)
