-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Server.Acl", function (namespace)
  -- <summary>
  -- Class that wraps static ACL functions
  -- </summary>
  namespace.class("AclFile", function (namespace)
    local Reload, Save
    -- <summary>
    -- This function reloads the ACL's and the ACL groups from the ACL XML file. All ACL and ACL group elements are invalid after a call to this and should not be used anymore.
    -- </summary>
    Reload = function ()
      return SlipeMtaDefinitions.MtaServer.AclReload()
    end
    -- <summary>
    -- The ACL XML file is automatically saved whenever the ACL is modified, but the automatic save can be delayed by up to 10 seconds for performance reasons. Calling this function will force an immediate save.
    -- </summary>
    Save = function ()
      return SlipeMtaDefinitions.MtaServer.AclSave()
    end
    return {
      Reload = Reload,
      Save = Save,
      __metadata__ = function (out)
        return {
          methods = {
            { "Reload", 0x8E, Reload, System.Boolean },
            { "Save", 0x8E, Save, System.Boolean }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
