-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Peds", function (namespace)
  -- <summary>
  -- Represents the fighting style of a ped
  -- </summary>
  namespace.enum("FightingStyle", function ()
    return {
      Standard = 4,
      Boxing = 5,
      Kung_Fu = 6,
      Knee_Head = 7,
      Grab_Kick = 15,
      Elbows = 16
    }
  end)
end)
