-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Shared.Helpers", function (namespace)
  -- <summary>
  -- Represents a handler for the server or client Mta version and Os info
  -- </summary>
  namespace.class("SystemVersion", function (namespace)
    local __ctor__
    -- <summary>
    -- Create a new version object
    -- </summary>
    __ctor__ = function (this)
      local dictionary = SlipeMtaDefinitions.MtaShared.GetDictionaryFromTable(SlipeMtaDefinitions.MtaShared.GetVersion(), "System.String", "System.String")
      this.Number = System.Int32.Parse(dictionary:get("number"))
      this.Mta = dictionary:get("mta")
      this.Name = dictionary:get("name")
      this.Netcode = dictionary:get("netcode")
      this.Os = dictionary:get("os")
      this.Type = dictionary:get("type")
      this.Tag = dictionary:get("tag")
      this.Sortable = dictionary:get("sortable")
    end
    return {
      Number = 0,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          properties = {
            { "Mta", 0x6, System.String },
            { "Name", 0x6, System.String },
            { "Netcode", 0x6, System.String },
            { "Number", 0x6, System.Int32 },
            { "Os", 0x6, System.String },
            { "Sortable", 0x6, System.String },
            { "Tag", 0x6, System.String },
            { "Type", 0x6, System.String }
          },
          methods = {
            { ".ctor", 0x6, nil }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
