-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Rendering", function (namespace)
  -- <summary>
  -- Represents camera fades
  -- </summary>
  namespace.enum("CameraFade", function ()
    return {
      In = 0,
      Out = 1
    }
  end)
end)
