-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Shared.Elements", function (namespace)
  -- <summary>
  -- Represents the type of an Mta Element
  -- </summary>
  namespace.enum("ElementType", function ()
    return {
      Element = 0,
      Player = 1,
      Ped = 2,
      Vehicle = 3,
      Object = 4,
      Pickup = 5,
      Marker = 6,
      ColShape = 7,
      Blip = 8,
      RadarArea = 9,
      Projectile = 10,
      Team = 11,
      GuiButton = 12,
      GuiBrowser = 13,
      GuiCheckBox = 14,
      GuiComboBox = 15,
      GuiEdit = 16,
      GuiGridList = 17,
      GuiMemo = 18,
      GuiProgressBar = 19,
      GuiRadioButton = 20,
      GuiScrollBar = 21,
      GuiScrollPane = 22,
      GuiStaticImage = 23,
      GuiTabPanel = 24,
      GuiTab = 25,
      GuiLabel = 26,
      GuiWindow = 27,
      Sound = 28,
      Weapon = 29,
      Effect = 30,
      Browser = 31,
      Light = 32,
      SearchLight = 33,
      Water = 34,
      Resource = 35,
      Root = 36
    }
  end)
end)
