-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Accounts", function (namespace)
  namespace.class("AccountException", function (namespace)
    local __ctor__
    __ctor__ = function (this, message)
      System.Exception.__ctor__(this, message)
    end
    return {
      __inherits__ = function (out, this)
        local base = System.Exception
        this.__tostring = base.__tostring
        return {
          base
        }
      end,
      __ctor__ = __ctor__,
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, nil, System.String }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
