-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Server.Game", function (namespace)
  -- <summary>
  -- Represents a server config bandwidth reduction setting
  -- </summary>
  namespace.enum("BandwidthReduction", function ()
    return {
      None = 0,
      Medium = 1,
      Maximum = 2
    }
  end)
end)
