-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
end)
System.namespace("Slipe.Server.Game", function (namespace)
  namespace.class("Settings", function (namespace)
    local Set, Get
    -- <summary>
    -- Stores arbitrary data in settings registry
    -- </summary>
    -- <param name="value"></param>
    Set = function (setting, value)
      SlipeMtaDefinitions.MtaServer.Set(setting, value)
    end
    -- <summary>
    -- Retrieves arbitrary data from settings registry
    -- </summary>
    -- <returns></returns>
    Get = function (setting)
      return SlipeMtaDefinitions.MtaServer.Get(setting)
    end
    return {
      Set = Set,
      Get = Get,
      __metadata__ = function (out)
        return {
          methods = {
            { "Get", 0x18E, Get, System.String, System.Object },
            { "Set", 0x20E, Set, System.String, System.Object }
          },
          class = { 0xE }
        }
      end
    }
  end)
end)
