-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents text alignment in gui's
  -- </summary>
  namespace.enum("HorizontalAlign", function ()
    return {
      Left = 0,
      Center = 1,
      Right = 2
    }
  end)

  namespace.enum("VerticalAlign", function ()
    return {
      Top = 0,
      Center = 1,
      Bottom = 2
    }
  end)
end)
