-- Generated by CSharp.lua Compiler
local System = System
local SlipeMtaDefinitions
local SlipeSharedElements
System.import(function (out)
  SlipeMtaDefinitions = Slipe.MtaDefinitions
  SlipeSharedElements = Slipe.Shared.Elements
end)
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents a custom Gui Font
  -- </summary>
  namespace.class("GuiFont", function (namespace)
    local __ctor1__, __ctor2__
    __ctor1__ = function (this, element)
      SlipeSharedElements.Element.__ctor__[2](this, element)
    end
    __ctor2__ = function (this, filePath, size)
      __ctor1__(this, SlipeMtaDefinitions.MtaClient.GuiCreateFont(filePath, size))
    end
    return {
      __inherits__ = function (out)
        return {
          out.Slipe.Shared.Elements.Element
        }
      end,
      __ctor__ = {
        __ctor1__,
        __ctor2__
      },
      __metadata__ = function (out)
        return {
          methods = {
            { ".ctor", 0x106, __ctor1__, out.Slipe.MtaDefinitions.MtaElement },
            { ".ctor", 0x206, __ctor2__, System.String, System.Int32 }
          },
          class = { 0x6 }
        }
      end
    }
  end)
end)
