-- Generated by CSharp.lua Compiler
local System = System
System.namespace("Slipe.Client.Gui", function (namespace)
  -- <summary>
  -- Represents standard Gui fonts
  -- </summary>
  namespace.enum("StandardGuiFont", function ()
    return {
      Default_Normal = 0,
      Default_Small = 1,
      Default_Bold_Small = 2,
      Clear_Normal = 3,
      Sa_Header = 4,
      Sa_Gothic = 5
    }
  end)
end)
